apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  creationTimestamp: "2020-01-07T00:36:44Z"
  generation: 5
  labels:
    machine.openshift.io/cluster-api-cluster: 9935-cwrbw
    machine.openshift.io/cluster-api-machine-role: worker
    machine.openshift.io/cluster-api-machine-type: worker
  name: general-purpose-1a
  namespace: openshift-machine-api
  resourceVersion: "266527"
  selfLink: /apis/machine.openshift.io/v1beta1/namespaces/openshift-machine-api/machinesets/general-purpose-1a
  uid: c7a17410-30e5-11ea-85a9-fa163e502ee1
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: 9935-cwrbw
      machine.openshift.io/cluster-api-machineset: general-purpose-1a
  template:
    metadata:
      creationTimestamp: null
      labels:
        machine.openshift.io/cluster-api-cluster: 9935-cwrbw
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: general-purpose-1a
    spec:
      metadata:
        creationTimestamp: null
        labels:
          failure-domain.beta.kubernetes.io/region: east
          failure-domain.beta.kubernetes.io/zone: 1a
          node-role.kubernetes.io/general-use: ""
      providerSpec:
        value:
          apiVersion: openstackproviderconfig.openshift.io/v1alpha1
          cloudName: openstack
          cloudsSecret:
            name: openstack-cloud-credentials
            namespace: openshift-machine-api
          flavor: 4c12g30d
          image: rhcos-ocp42
          kind: OpenstackProviderSpec
          networks:
          - filter: {}
            subnets:
            - filter:
                name: 9935-ocp-subnet
          securityGroups:
          - filter: {}
            name: 9935-worker_sg
          serverMetadata:
            Name: 9935-cwrbw-worker
            openshiftClusterID: 9935-cwrbw
          tags:
          - openshiftClusterID=9935-cwrbw
          trunk: true
          userDataSecret:
            name: worker-user-data
status:
  availableReplicas: 1
  fullyLabeledReplicas: 1
  observedGeneration: 5
  readyReplicas: 1
  replicas: 1
