apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: 9935-cwrbw
    machine.openshift.io/cluster-api-machine-role: worker
    machine.openshift.io/cluster-api-machine-type: worker
  name: logging-1a
  namespace: openshift-machine-api
spec:
  replicas: 0
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: 9935-cwrbw
      machine.openshift.io/cluster-api-machineset: logging-1a
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: 9935-cwrbw
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: logging-1a
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/logging: ""
      providerSpec:
        value:
          apiVersion: openstackproviderconfig.openshift.io/v1alpha1
          cloudName: openstack
          cloudsSecret:
            name: openstack-cloud-credentials
            namespace: openshift-machine-api
          flavor: 4c12g30d
          image: rhcos-ocp42
          kind: OpenstackProviderSpec
          networks:
          - filter: {}
            subnets:
            - filter:
                name: 9935-ocp-subnet
          securityGroups:
          - filter: {}
            name: 9935-worker_sg
          serverMetadata:
            Name: 9935-cwrbw-worker
            openshiftClusterID: 9935-cwrbw
          tags:
          - openshiftClusterID=9935-cwrbw
          trunk: true
          userDataSecret:
            name: worker-user-data
      taints:
      - key: logging
        value: reserved
        effect: NoSchedule
      - key: logging
        value: reserved
        effect: NoExecute
